language: php

php:
  - 5.3
  - 5.2

mysql:
  adapter: mysql2
  database: rucku_migrations_test
  username: rucku_test
  encoding: utf8

before_script:
  - "mysql -e 'create database rucku_migrations_test;'"
  - "cp config/application.model config/application.ini"
  - "cp config/database.model config/database.ini"

script: 
  - phpunit --configuration tests/phpunit-travis.xml --coverage-text

